"use client";
import Navbar from "../../components/section/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "../../components/section/Footer";
import { CartContext } from "../../components/section/CartContext";
import { useState } from "react";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: {
    content: "width=device-width",
    initialScale: 1.0,
  },
};


export default function RootLayout ({
  children,
}: {
  children: React.ReactNode;
}) {
 
  return (
    <html lang="en">
      <head>
      <link href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto+Condensed&display=swap" rel="stylesheet">
      </link>
      </head>
      <body className={inter.className}>

          <CartContext>
            <Navbar />
            <main className="px-28">
            {children}
            <Footer />
            </main>
          </CartContext>
       

      </body>
    </html>
  );
}
